<div id="leftside">
	<h2 class="hide">Menu:</h2>

	<ul class="avmenu">
		<li><a href="index.html">Main layout</a></li>
		<li><a class="current" href="index2.html">2-column layout A</a></li>
		<li><a href="index3.html">2-column layout B</a></li>
		<li><a href="#">Subpage demo</a>
			<ul>
				<li><a href="#">Subpage 1</a></li>
				<li><a href="#">Subpage 2</a></li>
			</ul>
		</li>
		<li><a href="print.html">Print stylesheet</a></li>
	</ul>

	<div class="announce">
		<h2>Updates:</h2>
		<p><strong>Oct 14, 2010:</strong><br />Alternative version of <a href="http://andreasviklund.com/templates/andreas01/">andreas01</a> created, dark style!</p>
	</div>
</div>

<div id="contentwide">
	<h2>General information</h2>
	<p>This is a free and standards-compliant XHTML/CSS website template, a great tool that makes it possible for people with limited web design experience to build a really good website. You are completely free to make any changes and modifications that you may want to, and use the template for any purpose without any obligations or limitations. I kindly ask you to leave the original design credits in the footer to support my template design work, but it is not any requirement.</p>
	<img src="img/test2.jpg" height="160" width="120" class="right" alt="Example image - aligned to the right" />
	<p>This template has been ported into themes for a number of different blogs and content management systems. An official <a href="http://andreasviklund.com/wordpress-themes/">WordPress theme</a> version is available, and a number of customized versions for other systems are listed on the original <a href="http://andreasviklund.com/templates/andreas01/">andreas01 template page</a>. If you customize this template into a CMS theme for public distribution, feel free to contact the template designer to have your version added to the list.</p>

	<h3>Adding your own header image</h3>
	<p>The default header can easily be replaced with a header of your own choice. Just replace front.jpg with an image of your own! If you use the same file name and image size as the default image, 950x200 pixels, you don't need to edit the header image tag at all.</p>
</div>