<div id="leftside">
	<h2 class="hide">Menu:</h2>

	<ul class="avmenu">
		<li><a href="#">Test #1</a></li>
		<li><a class="current" href="#">Test #2</a></li>
		<li><a href="#">Test #3</a></li>
		<li><a href="#">Test #4</a>
			<ul>
				<li><a href="#">Subpage 1</a></li>
				<li><a href="#">Subpage 2</a></li>
			</ul>
		</li>
		<li><a href="#">Print stylesheet</a></li>
	</ul>

	<div class="announce">
		<h2>Updates:</h2>
		<p><strong>Oct 14, 2010:</strong><br />Alternative version of <a href="http://andreasviklund.com/templates/andreas01/">andreas01</a> created, dark style!</p>
	</div>
</div>

<div id="content-section"></div>