<div id="header">
	<h1><a href="index.html">CJAF Framework Test</a></h1>
	<div class="nav-primary"></div>
</div>

<img id="frontphoto" src="img/front.jpg" width="950" height="200" alt="" />

<div id="content-main"></div>

<div id="footer">
	<p><span>&copy; 2010 <a href="#">Nathan Anthony Sculli, Sr and Piotr Tomasik</a></span><br />
		Template design by <a href="http://andreasviklund.com/">Andreas Viklund</a></p>
</div>
